---
title: "Untitled"
author: "Laura Givens"
date: "2025-05-02"
output: html_document
---
# Load  
Load libraries  
```{r,message=FALSE}
library(phyloseq)
library(tidyverse)
library(ggplot2)
library(cowplot)
library(vegan)
```

Load data  
```{r load}
dir_data <- '/Users/lauragivens/Desktop/R/BZrookery_eDNA/Rdata'
dir_results <- "/Volumes/Fuji/Mangroves/2025_0319_Givens_Canty_Rookery_COI/cutadapt/results"

prune.wblanks.ps.troph <- readRDS(paste0(dir_results,"/prune.decontam.ps.troph.keepblanks.rds"))
ps.troph <- readRDS(paste0(dir_results,"/prune.decontam.ps.troph.rds"))
prune.wblanks.ps.bold <- readRDS(paste0(dir_results,"/prune.decontam.ps.bold.keepblanks.rds"))
ps.bold <- readRDS(paste0(dir_results,"/prune.decontam.ps.bold.rds"))

taxa <- readRDS(paste0(dir_results,"/taxtable.rds"))
taxa_troph <- readRDS(paste0(dir_results,"/taxtable.wtroph.rds"))
taxa_bold <- readRDS(paste0(dir_results,"/taxtable.bold.rds"))

curated_lulu <- readRDS(paste0(dir_results,'/lulu-clustertable.rds'))
curated_asv <- readRDS(paste0(dir_results,"/asvtable.rds"))
samplelist <- readRDS(paste0(dir_results,'/metadata.rds'))
```

Compare sequence distribution   
```{r}
plot_bar(ps.troph)
plot_bar(ps.bold)
```

```{r}
tab.troph <- otu_table(ps.troph) %>% as.matrix() %>% as.data.frame() %>% t()
tab.bold <- otu_table(ps.bold) %>% as.matrix() %>% as.data.frame() %>% t()
#rarecurve(tab.troph)
#rarecurve(tab.bold)
```


# Tax distribution by date  
Raw  
```{r taxdate}
ps.troph %>%
  plot_bar(., x="Month") + 
  geom_bar(stat='identity',position='stack',aes(fill=Species)) + 
  facet_wrap(~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')

ps.bold %>%
  plot_bar(., x="Month") + 
  geom_bar(stat='identity',position='stack',aes(fill=Species)) + 
  facet_wrap(~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')
```

```{r}
ps.bold %>%
  plot_bar(., x="Month") + 
  geom_bar(stat='identity',position='stack',aes(fill=Family)) + 
  facet_wrap(~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')
```

```{r}
ps.bold %>% subset_taxa(!is.na(Phylum)) %>% 
  plot_bar(., x="Month") + 
  geom_bar(stat='identity',position='stack',aes(fill=Phylum)) + 
  facet_wrap(~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt')) 
```

# Relative abundance  
```{r}
ps.bold.rel <- ps.bold %>% transform_sample_counts(.,function(x) x/sum(x) ) 
ps.bold.na.rel <- ps.bold %>% subset_taxa(!is.na(Phylum)) %>% transform_sample_counts(.,function(x) x/sum(x) ) 
ps.troph.rel <- ps.troph %>% transform_sample_counts(.,function(x) x/sum(x) ) 
```

```{r}
ps.bold.rel %>% plot_bar(x="Month") + geom_bar(stat="identity",position="stack",aes(fill=Family)) + facet_grid(Site~Rookery)
ps.bold.na.rel %>% plot_bar(x="Month") + geom_bar(stat="identity",position="stack",aes(fill=Family)) + facet_grid(Site~Rookery)
ps.troph.rel %>% plot_bar(x="Month") + geom_bar(stat="identity",position="stack",aes(fill=Family)) + facet_grid(Site~Rookery)
```


# Look for species of interest  
Crocodiles
birds 
```{r}
get_taxa_unique(ps.bold %>% subset_taxa(Phylum=="Chordata"),"Class")
```
```{r}
tax_table(ps.bold %>% subset_taxa(Phylum=="Chordata" & Class!="Actinopterygii" & Class != "Ascidiacea") %>% prune_taxa(taxa_sums(.)>0,.) %>% prune_samples(sample_sums(.)>0,.))
```



```{r}
save.image("RData/Comparisons.Rdata")
```

```{r}
sessionInfo()
```

