---
title: "07_SeqAnalysis"
author: "Laura Givens"
date: "2025-04-10"
output: html_document
---

# Load  
Load libraries  
```{r,message=FALSE}
library(phyloseq)
library(tidyverse)
library(ggplot2)
library(cowplot)
```

Load data  
```{r load}
ps <- readRDS(paste0(dir_results,"/ps.rds"))
ps.troph <- readRDS(paste0(dir_results,"/ps.troph.rds"))

taxa <- readRDS(paste0(dir_results,"/taxtable.rds"))
taxa_troph <- readRDS(paste0(dir_results,"/taxtable.wtroph.rds"))
curated_lulu <- readRDS(paste0(dir_results,'/lulu-clustertable.rds'))
curated_asv <- readRDS(paste0(dir_results,"/asvtable.rds"))
samplelist <- readRDS(paste0(dir_results,'/metadata.rds'))
```

# Phyloseq  
About the ps objects  
```{r ps}
ps
ps.troph
```

Prune ps  
```{r prune_ps}
prune.ps <- ps %>% 
  prune_samples(sample_sums(.)>50,.) %>%
  subset_samples(.,Rookery!='Blank' & Rookery != 'Practice') 
```

```{r prune_100}
top100 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:100]

t100.ps <- prune.ps %>% prune_taxa(top100, .) 
```

```{r prune_1pct}
mean_cutoff = 0.01
mean_test = function(x) {
  mean(x) >= mean_cutoff
}
 prune.ps.1pct <- prune.ps %>% transform_sample_counts(function(x) x/sum(x)) %>% 
   filter_taxa(mean_test, prune=TRUE)
```

Prune trophic ps  
```{r}
prune.ps.troph <- ps.troph %>% 
  prune_samples(sample_sums(.)>50,.) %>%
  subset_samples(.,Rookery!='Blank' & Rookery != 'Practice') 
```

# Descriptive Stats  
Sequence distribution  
```{r distribution}
plot_bar(ps)
```

Unique taxa  
```{r num_taxa}
  tibble(Rank = rank_names(ps)) %>% 
    rowwise %>%
    mutate(Unique = length(get_taxa_unique((ps),Rank)))
```

# Tax distribution by sample  
Raw  
```{r taxsam-raw}
ps %>%
  plot_bar(., x="Sample.Name") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_wrap(Site~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')
```

Pruned  
```{r taxsam-pr}
prune.ps %>%
  plot_bar(., x="Sample.Name") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_wrap(Site~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')
```

Top 100  
```{r taxsam-t100}
t100.ps %>% 
  plot_bar(., x="Sample.Name") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_grid(Site~Rookery,scales='free') + 
  theme(legend.position = 'none')
```

1 pct  
```{r taxsam-1pct}
prune.ps.1pct %>% 
  plot_bar(., x="Sample.Name") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_grid(Site~Rookery,scales='free_x') + 
  theme(legend.position = 'none')
```

# Tax distribution by date  
Raw  
```{r taxdate-raw}
ps %>%
  plot_bar(., x="Date") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_wrap(~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')
```

Pruned  
```{r taxdate-pr}
prune.ps %>%
  plot_bar(., x="Date") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_wrap(~Rookery,scales='free_x') + 
  theme(legend.key.size = unit(2,'pt'),
        legend.key.spacing = unit(0.1,'pt'),
        legend.position = 'none')
```

Top 100  
```{r taxdate-t100}
t100.ps %>% 
  plot_bar(., x="Date") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_grid(~Rookery,scales='free') + 
  theme(legend.position = 'none')
#ggsave("/Users/lauragivens/Downloads/t100.rookery.facet.png",height=10,width=15)
```

1 pct  
```{r taxdate-1pct}
prune.ps.1pct %>% 
  plot_bar(., x="Date") + 
  geom_bar(stat='identity',position='stack',aes(fill=species)) + 
  facet_grid(~Rookery,scales='free_x') + 
  theme(legend.position = 'none')
#ggsave("/Users/lauragivens/Downloads/prune.1pct.rookery.facet.png",height=10,width=20)
```

# PS trophic  
```{r}
ps.troph %>% 
  plot_bar(., x="Date") + 
  geom_bar(stat='identity',position='stack',aes(fill=Trophic.Index)) + 
  facet_grid(~Rookery,scales='free_x') + 
  theme(legend.position = 'none')
```


# Richness  
```{r rich-samplename}
plot_richness(ps,x="Sample.Name",measures = c("Observed","Shannon"),color="Rookery")
```

# Heatmap  
```{r hm}
plot_heatmap(prune.ps.1pct,taxa.label = 'species',sample.order='Date',taxa.order='family') + facet_wrap(~Rookery,scales='free')
#ggsave("/Users/lauragivens/Downloads/prune.1pct.heatmap.rookery.facet.png",width=15,height=5)
```

```{r}
ps.melt <- prune.ps.1pct %>% psmelt() 
ps.melt <- ps.melt %>% group_by(species) %>% reframe(Abund=sum(Abundance),Total=sum(.$Abundance),Perc=Abund/Total) %>% arrange(.,desc(Perc),.by_group=TRUE)

ps.melt$species <- factor(ps.melt$species,levels=ps.melt$species)

ggplot(ps.melt, aes(y=species,x=Perc,fill=species)) + geom_col() + theme(legend.position='none')
```



```{r session-info}
sessionInfo()
```
